version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Install curl

          command: sudo apt update && sudo apt install curl
      - run:
          name: Build docker
          command: docker build -t fa_nodejs_sample .

workflows:
  build:
    jobs:
      - test